name: conditional workflow

on:
  push:
    branches:
      - "backend/**"

jobs:
  conditional-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "conditional World"
