name: dependent multijob Workflow

on:
  push:
   branches:
    - main

jobs:
  first-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: first step
        run: echo "Hello World"

  second-workflow-job:
    
  
    runs-on: ubuntu-latest
    needs: [first-workflow-job]

    steps:
      - name: second step
        run: echo "Hello World"
  third-workflow-job:

    runs-on: ubuntu-latest
    needs: [first-workflow-job, second-workflow-job]

    steps:
      - name: second step
        run: echo "Hello World"
