name: multijob Workflow

on:
  branches:
    - main

jobs:
  first-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: first step
      run: echo "Hello World"
  second-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: second step
      run: echo "Hello World"
